name: Deploy to Kubernetes
on:
  push:
    branches: [main]  # or 'master' or any branch you prefer

jobs:
  deploy:
    runs-on: k8s

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Get short Git commit SHA
      id: vars
      run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and Push Docker
      working-directory: .
      run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/my-app:${{ env.COMMIT_SHA }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up kubeconfig
      run: |
        mkdir -p /root/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Change Deployment Image in Manifest
      run: |
        sed -i 's|image: .*|image: ghcr.io/'${{ github.repository }}'/my-app:'${{ env.COMMIT_SHA }}'|g' test-mainfest/nginx-deployment.yml
        cat test-mainfest/nginx-deployment.yml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f test-mainfest/
        kubectl get pods -n default
        kubectl get svc -n default
        kubectl delete -f test-mainfest/
    
    - name: Clean k8s cluster configuiration
      run: |
        rm -rf $HOME/.kube